function [] = s809gui()
% S809GUI Brief description of GUI.
%         Comments displayed at the command line in response
%         to the help command.

% Initialization Tasks
clear all;
format long;

% Construct the Components
S.fh = figure(... % The main GUI figure
            'MenuBar','none', ...
            'Toolbar','none', ...      
            'HandleVisibility','callback', ...
            'Visible','off', ...
            'Units','pixels', ...
            'Position',[0 0 1000 700]);
    S.ax = axes('Parent',S.fh, ...
                'Units','pixels', ...
                'Position',[50 50 550 625]);
    S.pnl(1) = uipanel('Parent',S.fh, ...
                'Title','File I/O', ...
                'FontSize',12, ... 
                'Units','Pixels', ...
                'Position',[625 650 375 50]);
        S.pb(1) = uicontrol('Parent',S.pnl(1),...
                            'Style','pushbutton',...
                            'String','Read ...',...
                            'FontSize',12,...
                            'Units','Pixels',...
                            'Position',[5 5 100 25]);    
        S.pb(2) = uicontrol('Parent',S.pnl(1),...
                            'Style','pushbutton',...
                            'String','Write ...',...
                            'FontSize',12,...
                            'Units','Pixels',...
                            'Position',[125 5 100 25]);     
    S.pnl(2) = uipanel('Parent',S.fh, ...
                'Title','Cubic Curve', ...
                'FontSize',12, ... 
                'Units','Pixels', ...
                'Position',[625 315 375 325]); 
        %%% X1 %%%            
        S.tx(1) = uicontrol('Parent',S.pnl(2), ...
                    'Style','text',...
                    'String','Start Pos',...
                    'Units','Pixels',...
                    'Position',[10 275 75 25]); 
        S.ed(1) = uicontrol('Parent',S.pnl(2), ...
                    'Style','edit',...
                    'String','0.25', ...
                    'BackgroundColor','white', ...
                    'Units','Pixels',...
                    'Position',[85 275 75 25]);
        S.pb(3) = uicontrol('Parent',S.pnl(2), ...
                    'Style','pushbutton',...
                    'String','<->',...
                    'Units','Pixels',...
                    'Position',[160 275 25 25]);              
        S.ed(2) = uicontrol('Parent',S.pnl(2), ...
                    'Style','edit',...
                    'String','0.25', ...
                    'BackgroundColor','white', ...
                    'Units','Pixels',...
                    'Position',[185 275 75 25]);
        S.tx(2) = uicontrol('Parent',S.pnl(2), ...
                    'Style','text',...
                    'String','0.05',...
                    'Units','Pixels',...
                    'Position',[10 245 50 25]);                
        S.sp(1) = uicontrol('Parent',S.pnl(2), ...
                    'Style','slider', ...
                    'Min',0.05, ...
                    'Max',0.9, ...
                    'Value',0.25, ...
                    'Units','pixels', ...
                    'Position',[65 245 225 25]);
        S.tx(3) = uicontrol('Parent',S.pnl(2), ...
                    'Style','text',...
                    'String','0.90',...
                    'Units','Pixels',...
                    'Position',[300 245 50 25]);                
        %%% X2 %%%                  
        S.tx(4) = uicontrol('Parent',S.pnl(2), ...
                    'Style','text',...
                    'String','Angle',...
                    'Units','Pixels',...
                    'Position',[10 215 75 25]); 
        S.ed(3) = uicontrol('Parent',S.pnl(2), ...
                    'Style','edit',...
                    'String','30', ...
                    'BackgroundColor','white', ...
                    'Units','Pixels',...
                    'Position',[85 215 75 25]);
        S.pb(4) = uicontrol('Parent',S.pnl(2), ...
                    'Style','pushbutton',...
                    'String','<->',...
                    'Units','Pixels',...
                    'Position',[160 215 25 25]);
        S.ed(4) = uicontrol('Parent',S.pnl(2), ...
                    'Style','edit',...
                    'String','0.0', ...                    
                    'BackgroundColor','white', ...
                    'Units','Pixels',...
                    'Position',[185 215 75 25]);
        S.tx(5) = uicontrol('Parent',S.pnl(2), ...
                    'Style','text',...
                    'String','0.0',...
                    'Units','Pixels',...
                    'Position',[10 185 50 25]);                
        S.sp(2) = uicontrol('Parent',S.pnl(2), ...
                    'Style','slider', ...
                    'Min',0.0, ...
                    'Max',135.0, ...
                    'Value',30.0, ...                    
                    'Units','pixels', ...
                    'Position',[65 185 225 25]);  
        S.tx(6) = uicontrol('Parent',S.pnl(2), ...
                    'Style','text',...
                    'String','135',...
                    'Units','Pixels',...
                    'Position',[300 185 50 25]);                
        %%% X3 %%%                       
        S.tx(7) = uicontrol('Parent',S.pnl(2), ...
                    'Style','text',...
                    'String','Scale Vec 1',...
                    'Units','Pixels',...
                    'Position',[10 155 75 25]); 
        S.ed(5) = uicontrol('Parent',S.pnl(2), ...
                    'Style','edit',...
                    'String','0.25', ...
                    'BackgroundColor','white', ...
                    'Units','Pixels',...
                    'Position',[85 155 75 25]);
        S.pb(5) = uicontrol('Parent',S.pnl(2), ...
                    'Style','pushbutton',...
                    'String','<->',...
                    'Units','Pixels',...
                    'Position',[160 155 25 25]);  
        S.ed(6) = uicontrol('Parent',S.pnl(2), ...
                    'Style','edit',...
                    'String','0.0', ...                    
                    'BackgroundColor','white', ...
                    'Units','Pixels',...
                    'Position',[185 155 75 25]);
        S.tx(8) = uicontrol('Parent',S.pnl(2), ...
                    'Style','text',...
                    'String','0.05',...
                    'Units','Pixels',...
                    'Position',[10 125 50 25]);                
        S.sp(3) = uicontrol('Parent',S.pnl(2), ...
                    'Style','slider', ...
                    'Min',0.05, ...
                    'Max',5.0, ...
                    'Value',0.25, ...                    
                    'Units','pixels', ...
                    'Position',[65 125 225 25]);  
        S.tx(9) = uicontrol('Parent',S.pnl(2), ...
                    'Style','text',...
                    'String','5',...
                    'Units','Pixels',...
                    'Position',[300 125 50 25]);                
        %%% X4 %%%                
        S.tx(10) = uicontrol('Parent',S.pnl(2), ...
                    'Style','text',...
                    'String','Scale Vec 2',...
                    'Units','Pixels',...
                    'Position',[10 95 75 25]); 
        S.ed(7) = uicontrol('Parent',S.pnl(2), ...
                    'Style','edit',...
                    'String','0.75', ...
                    'BackgroundColor','white', ...
                    'Units','Pixels',...
                    'Position',[85 95 75 25]);
        S.pb(6) = uicontrol('Parent',S.pnl(2), ...
                    'Style','pushbutton',...
                    'String','<->',...
                    'Units','Pixels',...
                    'Position',[160 95 25 25]);   
        S.ed(8) = uicontrol('Parent',S.pnl(2), ...
                    'Style','edit',...
                    'String','0.0', ...                    
                    'BackgroundColor','white', ...
                    'Units','Pixels',...
                    'Position',[185 95 75 25]);
        S.tx(11) = uicontrol('Parent',S.pnl(2), ...
                    'Style','text',...
                    'String','0.05',...
                    'Units','Pixels',...
                    'Position',[10 65 50 25]);                
        S.sp(4) = uicontrol('Parent',S.pnl(2), ...
                    'Style','slider', ...
                    'Min',0.05, ...
                    'Max',5.0, ...
                    'Value',0.75, ...                    
                    'Units','pixels', ...
                    'Position',[65 65 225 25]); 
        S.tx(12) = uicontrol('Parent',S.pnl(2), ...
                    'Style','text',...
                    'String','5',...
                    'Units','Pixels',...
                    'Position',[300 65 50 25]);                
        %%% X5 %%%                
        S.tx(13) = uicontrol('Parent',S.pnl(2), ...
                    'Style','text',...
                    'String','End Pos',...
                    'Units','Pixels',...
                    'Position',[10 35 75 25]); 
        S.ed(9) = uicontrol('Parent',S.pnl(2), ...
                    'Style','edit',...
                    'String','0.75', ...
                    'BackgroundColor','white', ...
                    'Units','Pixels',...
                    'Position',[85 35 75 25]);
        S.pb(7) = uicontrol('Parent',S.pnl(2), ...
                    'Style','pushbutton',...
                    'String','<->',...
                    'Units','Pixels',...
                    'Position',[160 35 25 25]);        
        S.ed(10) = uicontrol('Parent',S.pnl(2), ...
                    'Style','edit',...
                    'String','0.0', ...                    
                    'BackgroundColor','white', ...
                    'Units','Pixels',...
                    'Position',[185 35 75 25]); 
        S.tx(14) = uicontrol('Parent',S.pnl(2), ...
                    'Style','text',...
                    'String','0.1',...
                    'Units','Pixels',...
                    'Position',[10 5 50 25]);                
        S.sp(5) = uicontrol('Parent',S.pnl(2), ...
                    'Style','slider', ...
                    'Min',0.1, ...
                    'Max',0.95, ...
                    'Value',0.75, ...                    
                    'Units','Pixels', ...
                    'Position',[65 5 225 25]);
        S.tx(15) = uicontrol('Parent',S.pnl(2), ...
                    'Style','text',...
                    'String','0.95',...
                    'Units','Pixels',...
                    'Position',[300 5 50 25]);                
    S.pnl(3) = uipanel('Parent',S.fh, ...
                'Title','Setup', ...
                'FontSize',12, ... 
                'Units','Pixels', ...
                'Position',[625 190 375 125]);              
        S.bg(1) = uibuttongroup('Parent',S.pnl(3), ...
                    'Title','Parameterization', ...
                    'Units','Pixels', ...
                    'Position',[1 1 98 100]);
            S.rd(1) = uicontrol('Parent',S.bg(1), ...
                    'Style','radio', ...
                    'String','uniform', ...
                    'Units','pixels', ...
                    'Position',[1 50 75 23]);
            S.rd(2) = uicontrol('Parent',S.bg(1), ...
                    'Style','radio', ...
                    'String','chordlength', ...
                    'Units','pixels', ...
                    'Position',[1 25 75 23]);
            S.rd(3) = uicontrol('Parent',S.bg(1), ...
                    'Style','radio', ...
                    'String','centripetal', ...
                    'Units','pixels', ...
                    'Position',[1 1 75 23]);               
        S.bg(2) = uibuttongroup('Parent',S.pnl(3), ...
                    'Title','Boundary Conditions', ...
                    'Units','Pixels', ...
                    'Position',[100 1 125 100]);
            S.rd(4) = uicontrol('Parent',S.bg(2), ...
                    'Style','radio', ...
                    'String','natural', ...
                    'Units','pixels', ...
                    'Position',[1 50 75 23]);
            S.rd(5) = uicontrol('Parent',S.bg(2), ...
                    'Style','radio', ...
                    'String','not-a-knot', ...
                    'Units','pixels', ...
                    'Position',[1 25 75 23]); 
        S.tx(18) = uicontrol('Parent',S.pnl(3), ...
                    'Style','text',...
                    'String','np =',...
                    'Units','Pixels',...
                    'Position',[225 65 50 25]); 
        S.ed(11) = uicontrol('Parent',S.pnl(3), ...
                    'Style','edit',...
                    'String','100', ... 
                    'BackgroundColor','white', ...
                    'Units','Pixels',...
                    'Position',[275 65 75 25]);
        S.tx(19) = uicontrol('Parent',S.pnl(3), ...
                    'Style','text',...
                    'String','tol =',...
                    'Units','Pixels',...
                    'Position',[225 35 50 25]); 
        S.ed(12) = uicontrol('Parent',S.pnl(3), ...
                    'Style','edit',...
                    'String','0.00001', ...
                    'BackgroundColor','white', ...
                    'Units','Pixels',...
                    'Position',[275 35 75 25]);
        S.tx(20) = uicontrol('Parent',S.pnl(3), ...
                    'Style','text',...
                    'String','iter =',...
                    'Units','Pixels',...
                    'Position',[225 5 50 25]); 
        S.ed(13) = uicontrol('Parent',S.pnl(3), ...
                    'Style','edit',...
                    'String','100', ...
                    'BackgroundColor','white', ...
                    'Units','Pixels',...
                    'Position',[275 5 75 25]);                               
    S.pnl(4) = uipanel('Parent',S.fh, ...
                'Title','Axes', ...
                'FontSize',12, ... 
                'Units','Pixels', ...
                'Position',[625 5 375 175]); 
            S.tg(1) = uicontrol('Parent',S.pnl(4),...
                                'Style','togglebutton',...
                                'String','Pan',...
                                'FontSize',12,...
                                'Units','Pixels',...
                                'Position',[5 125 100 25]); 
            S.tg(2) = uicontrol('Parent',S.pnl(4),...
                                'Style','togglebutton',...
                                'String','Zoom',...
                                'FontSize',12,...
                                'Units','Pixels',...
                                'Position',[125 125 100 25]);                         
% --- Figure: Axes: x limit --- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            S.tx(23) = uicontrol('Parent',S.pnl(4), ...
                        'Style','text',...
                        'String','x limit',...   
                        'FontSize',12, ...                        
                        'Units','Pixels',...
                        'Position',[10 85 75 25]); 
            S.ed(18) = uicontrol('Parent',S.pnl(4), ...
                        'Style','edit',...
                        'BackgroundColor','white', ...
                        'Units','Pixels',...
                        'Position',[85 85 75 25]);
            S.tx(24) = uicontrol('Parent',S.pnl(4), ...
                        'Style','text',...
                        'String','to',...       
                        'FontSize',12, ...                         
                        'Units','Pixels',...
                        'Position',[160 85 25 25]);
            S.ed(19) = uicontrol('Parent',S.pnl(4), ...
                        'Style','edit',...
                        'BackgroundColor','white', ...
                        'Units','Pixels',...
                        'Position',[185 85 75 25]);
            S.ch(1) = uicontrol('Parent',S.pnl(4), ...
                        'Style','checkbox',...           
                        'Units','Pixels',...
                        'Position',[265 95 25 25]);
            S.tx(25) = uicontrol('Parent',S.pnl(4), ...
                        'Style','text',...
                        'String','Auto',...       
                        'FontSize',12, ...  
                        'HorizontalAlignment','left', ...                        
                        'Units','Pixels',...
                        'Position',[290 95 75 25]);                
            S.ch(2) = uicontrol('Parent',S.pnl(4), ...
                        'Style','checkbox',...           
                        'Units','Pixels',...
                        'Position',[265 65 25 25]);
            S.tx(26) = uicontrol('Parent',S.pnl(4), ...
                        'Style','text',...
                        'String','Reverse',...   
                        'FontSize',12, ...    
                        'HorizontalAlignment','left', ...
                        'Units','Pixels',...
                        'Position',[290 65 75 25]);        
% --- Figure: Axes: y limit --- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            S.tx(27) = uicontrol('Parent',S.pnl(4), ...
                        'Style','text',...
                        'String','y limit',...  
                        'FontSize',12, ...
                        'Units','Pixels',...                       
                        'Position',[10 25 75 25]); 
            S.ed(20) = uicontrol('Parent',S.pnl(4), ...
                        'Style','edit',...
                        'BackgroundColor','white', ...            
                        'Units','Pixels',...
                        'Position',[85 25 75 25]);
            S.tx(28) = uicontrol('Parent',S.pnl(4), ...
                        'Style','text',...
                        'String','to',...      
                        'FontSize',12, ...                                                
                        'Units','Pixels',...
                        'Position',[160 25 25 25]);
            S.ed(21) = uicontrol('Parent',S.pnl(4), ...
                        'Style','edit',...
                        'BackgroundColor','white', ...            
                        'Units','Pixels',...
                        'Position',[185 25 75 25]);
            S.ch(3) = uicontrol('Parent',S.pnl(4), ...
                        'Style','checkbox',...                         
                        'Units','Pixels',...
                        'Position',[265 35 25 25]);
            S.tx(29) = uicontrol('Parent',S.pnl(4), ...
                        'Style','text',...
                        'String','Auto',...    
                        'FontSize',12, ...    
                        'HorizontalAlignment','left', ...                                              
                        'Units','Pixels',...
                        'Position',[290 35 75 25]);                
            S.ch(4) = uicontrol('Parent',S.pnl(4), ...
                        'Style','checkbox',...           
                        'Units','Pixels',...                       
                        'Position',[265 5 25 25]);
            S.tx(30) = uicontrol('Parent',S.pnl(4), ...
                        'Style','text',...
                        'String','Reverse',... 
                        'FontSize',12, ...
                        'HorizontalAlignment','left', ...                        
                        'Units','Pixels',...
                        'Position',[290 5 75 25]);       
            S.ch(5) = uicontrol('Parent',S.pnl(4), ...
                        'Style','checkbox',...           
                        'Units','Pixels',...                       
                        'Position',[265 125 25 25]);
            S.tx(31) = uicontrol('Parent',S.pnl(4), ...
                        'Style','text',...
                        'String','Show control points',... 
                        'HorizontalAlignment','left', ...                        
                        'Units','Pixels',...
                        'Position',[290 125 75 25]);                         
% --- step width and height --- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    S.tx(32) = uicontrol('Parent',S.fh, ...
                'Style','text', ...
                'String','Step Height = ', ...
                'HorizontalAlignment','left', ...                        
                'Units','Pixels',...
                'Position',[50 5 150 25]);  
    S.tx(33) = uicontrol('Parent',S.fh, ...
                'Style','text', ...
                'String','0.0', ...
                'HorizontalAlignment','left', ...                        
                'Units','Pixels',...
                'Position',[200 5 100 25]);
	S.tx(34) = uicontrol('Parent',S.fh, ...
                'Style','text', ...
                'String','Step Width = ', ...
                'HorizontalAlignment','left', ...                        
                'Units','Pixels',...
                'Position',[300 5 150 25]);
	S.tx(35) = uicontrol('Parent',S.fh, ...
                'Style','text', ...
                'String','0.0', ...
                'HorizontalAlignment','left', ...                        
                'Units','Pixels',...
                'Position',[450 5 100 25]);
            
% Initialization Tasks
set(S.fh,'CurrentAxes',S.ax);
setAxes(S);
set(S.bg(1),'SelectedObject',S.rd(2));
set(S.bg(2),'SelectedObject',S.rd(5));

% Callbacks for GUI
set(S.pb(1),'Callback',{'read_Callback',S});
set(S.pb(2),'Callback',{'write_Callback',S});

set(S.pb(3:7),'Callback',{'sto_Callback',S});
set(S.sp(1:5),'Callback',{'sp_Callback',S});
set([S.ed(1),S.ed(3),S.ed(5),S.ed(7),S.ed(9),S.ed(11:13)],'Callback',{'ed_Callback',S});

set(S.tg(1),'Callback',{'pan_Callback',S});
set(S.tg(2),'Callback',{'zoom_Callback',S});

set(S.ed(18:19),'Callback',{'xlim_Callback',S});
set(S.ch(1),'Callback',{'xauto_Callback',S});
set(S.ch(2),'Callback',{'xrev_Callback',S});

set(S.ed(20:21),'Callback',{'ylim_Callback',S});
set(S.ch(3),'Callback',{'yauto_Callback',S});
set(S.ch(4),'Callback',{'yrev_Callback',S});

set(S.ch(5),'Callback',{'cp_Callback',S});

% Initialization Tasks
set(S.fh,'Name','JetSoft');
movegui(S.fh,'northwest');    
set(S.fh,'Visible','on');

end